# Supabase Configuration File

[functions.api]
entrypoint = './functions/api/index.tsx'

[functions.data-migration]
entrypoint = './functions/data-migration/index.tsx'

# Enable all the shared files to be accessible
[functions]
# Global function settings

[functions.test-minimal]
enabled = true
verify_jwt = true
import_map = "./functions/test-minimal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-minimal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-minimal/*.html" ]
