/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eezimywnyqzbtqqwbqqr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlemlteXdueXF6YnRxcXdicXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTE5MjYsImV4cCI6MjA3MTM2NzkyNn0.WjocfbV5d7OJ_-LJBsT5248uXRfp9yL-2ZHmOSbJD0k"